baseurl: //ericbouchut.com
title: Eric Bouchut
theme: hugo-tranquilpeak-theme
languageCode: en-us
defaultContentLanguage: "en-us"
metaDataFormat: yaml
canonifyurls: false
disqusShortname: "ericbouchut"
permalinks:
  post: /:year/:month/:day/:title/
taxonomies:
  tag: tags
  category: categories
editor: vim
author:
  name: Eric Bouchut
  bio: Ruby on Rails aficionado, en route to becoming a Blockchain and Smart Contracts developer
  job: Ruby on Rails developer at S4M
  location: Aix-en-Provence, France
  gravatarEmail: ericbouchut@gmail.com
  #  picture: https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png
  twitter: ebouchut

#~~~~~~~~~~~~~~~~
# Markdown Engine
#~~~~~~~~~~~~~~~~
blackfriday:
  smartypants: false

#~~~~~~~~~~~~~~~~
# Colorize Syntax
#~~~~~~~~~~~~~~~~
# Use CSS classes instead of color codes for syntax coloring
# pygmentsUseClasses: true
# pygmentsStyle: "monokai"
# Use triple back ticks (Github Flavored Markdown) to denote a code block
# pygmentsCodeFences: true
# enables syntax guessing for code fences without specified language
# pygmentsCodeFencesGuessSyntax: true

params:
  sidebarBehavior: 2
  clearReading: true
  coverImage: images/cover-v1.2.0.jpg
  imageGallery: true
  thumbnailImage: true
  thumbnailImagePosition: left
  googleAnalytics: UA-610695-2
  comments: false
  hierarchicalCategories: true

menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      pre: <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      url: "/"
    - name: About
      weight: 20
      identifier: about
      pre: <i class="sidebar-button-icon fa fa-lg fa-user"></i>
      url: "/about"
    - name: Contact
      weight: 30
      identifier: contact
      pre: <i class="sidebar-button-icon fa fa-lg fa-envelope"></i>
      url: "/contact"
  links:
    - name: LinkedIn
      weight: 10
      identifier: linkedin
      pre: <i class="sidebar-button-icon fab fa-linkedin-in"></i>
      url: https://linkedin.com/in/ebouchut
    - name: Github
      weight: 20
      identifier: github
      pre: <i class="sidebar-button-icon fab fa-github"></i>
      url: https://github.com/ebouchut
    - name: Twitter
      weight: 30
      identifier: twitter
      pre: <i class="sidebar-button-icon fab fa-twitter"></i>
      url: https://twitter.com/ebouchut
    - name: Blockchain
      weight: 40
      identifier: blockchain
      pre: <i class="sidebar-button-icon fab fa-ethereum"></i>
      url: https://github.com/bet-no-loss/bet-no-loss#readme

  misc:
    - name: "Categories"
      identifier: "categories"
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
      url: "/categories"
      weight: 10
    - name: "Tags"
      weight: 20
      identifier: "tags"
      pre: <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      url: "/tags"
    - name: "RSS"
      identifier: rss
      pre: <i class="sidebar-button-icon fa fa-lg fa-rss"></i>
      url: "/index.xml"
      weight: 99
...
